#!/bin/bash

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}


#########################################################################################
function port_is_ok() {
    local port="$1"
	
    local -i port_num=$(to_int "${port}" 2>/dev/null)
   	
		
    if (( $port_num < 1 || $port_num > 65535 )) ; then
       return 1 
    else
	return 0
	fi
}
function to_int {
    local -i num="10#${1}"
    echo "${num}"
}
#########################################################################################
AllFile=true

FILE=/etc/asterisk/http.conf
if ! [ -f "$FILE" ]; then
    echo "$FILE does not exist , Asterisk is not installed correctly !!"
	AllFile=false
fi

FILE=/etc/asterisk/sip.conf
if ! [ -f "$FILE" ]; then
    echo "$FILE does not exist , Asterisk is not installed correctly !!"
	AllFile=false
fi

FILE=/etc/asterisk/extensions.conf
if ! [ -f "$FILE" ]; then
    echo "$FILE does not exist , Asterisk is not installed correctly !!"
	AllFile=false
fi
FILE=/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini
if ! [ -f "$FILE" ]; then
    echo "$FILE does not exist , Kurento is not installed correctly !!"
	AllFile=false
fi

##############################################################################################


if [ "$AllFile" = true ] ; then


echo "Enter the IP address of this server - or enter q to skip :"
read srvip
if ! [ "$srvip" = 'q' ] ; then
while ! valid_ip $srvip
do
   echo "Bad IP Address"
echo "Please Re-Enter the IP address of this server - or enter q to skip : :"
read srvip
done


if valid_ip $srvip
then
sed -i "s+bindaddr=.*+bindaddr=$srvip+g" "/etc/asterisk/http.conf"
sed -i "s+tlsbindaddr=.*+tlsbindaddr=$srvip:8089+g" "/etc/asterisk/http.conf"
sed -i "s+realm=.*+realm=$srvip+g" "/etc/asterisk/sip.conf"
sed -i "s+udpbindaddr=.*+udpbindaddr=$srvip+g" "/etc/asterisk/sip.conf"

#sed -i "s/10.20.30.215/$srvip/g"  "/etc/asterisk/http.conf"
#sed -i "s/10.20.30.215/$srvip/g" "/etc/asterisk/sip.conf"

else echo "Bad IP Address"
fi
fi
########################################################################################
echo "Enter the STUN IP Address - or enter q to skip  :"
read stunIP
if ! [ "$stunIP" = 'q' ] ; then
while ! valid_ip $stunIP
do
   echo "Bad STUN IP Address"
echo "Please Re-Enter the STUN IP address :"
read stunIP
done

if valid_ip $stunIP
then
sed -i "s+;stunServerAddress=<IpAddress>+stunServerAddress=$stunIP+g" "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
sed -i "s+stunServerAddress=.*+stunServerAddress=$stunIP+g" "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
else echo "Bad STUN IP Address"
fi
fi
############################################################################################
echo "Enter the STUN Port number - or enter q to skip :"
read stunprt
if ! [ "$stunprt" = 'q' ] ; then
while ! port_is_ok $stunprt ; do
echo "STUN Port number is not Valid !!"
echo "Enter a Valid STUN Port number:"
read stunprt
done

sed -i "s+;stunServerPort=<Port>+stunServerPort=$stunprt+g" "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"
sed -i "s+stunServerPort=.*+stunServerPort=$stunprt+g" "/etc/kurento/modules/kurento/WebRtcEndpoint.conf.ini"

fi
##############################################################################################
echo "Enter the CUCM IP Address - or enter q to skip :"
read cucmIP
if ! [ "$cucmIP" = 'q' ] ; then
while ! valid_ip $cucmIP

do
   echo "Bad CUCM IP Address"
echo "Please Re-Enter the CUCM IP address  :"
read cucmIP
done

if valid_ip $cucmIP
then
sed -i "s+^host=[0-9].*+host=$cucmIP+g" "/etc/asterisk/sip.conf"
else echo "Bad CUCM IP Address"
fi
fi

##############################################################################################

echo "Enter the CUCM Port - or enter q to skip :"
read cucmprt
if ! [ "$cucmprt" = 'q' ] ; then
while ! port_is_ok $cucmprt ; do
echo "CUCM Port number is not Valid !!"
echo "Enter a Valid CUCM Port number:"
read cucmprt
done
sed -i "s+\bport\b=.*+port=$cucmprt+g" "/etc/asterisk/sip.conf"
fi
#############################################################################################

echo "Enter the full path for crt file - or enter q to skip:"
read crt
if ! [ "$crt" = 'q' ] ; then

#if ! [ -f "$crt" ]; then
#    echo "$crt does not exist"
#else
sed -i "s+tlscertfile=.*+tlscertfile=$crt+g"  "/etc/asterisk/http.conf"
sed -i "s+dtlscertfile=.*+dtlscertfile=$crt+g" "/etc/asterisk/sip.conf"
#fi
fi

echo "Enter the full path for key file - or enter q to skip:"
read crt1
if ! [ "$crt1" = 'q' ] ; then
sed -i "s+tlsprivatekey=.*+tlsprivatekey=$crt1+g" "/etc/asterisk/http.conf"
sed -i "s+dtlsprivatekey=.*+dtlsprivatekey=$crt1+g"  "/etc/asterisk/sip.conf"
fi

##########################################################################################

echo "Enter the Username for asterisk - or enter q to skip:"
read un1
if ! [ "$un1" = 'q' ] ; then
sed -i "s+^\[[0-9].*+\[$un1\]+g" "/etc/asterisk/sip.conf"
sed -i "s+username=.*+username=$un1+g"  "/etc/asterisk/sip.conf"
sed -i "s+^exten => [0-9].*+exten => $un1,1,Dial(SIP/$un1)+g"  "/etc/asterisk/extensions.conf"
fi

####################################################################

echo "Enter the password for asterisk user - or enter q to skip:"
read ps1
if ! [ "$ps1" = 'q' ] ; then
sed -i "s+secret=.*+secret=$ps1+g"  "/etc/asterisk/sip.conf"
fi
fi
service asterisk stop
service asterisk start
service kurento-media-server stop
 service kurento-media-server start
